language: r
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: 
        - xcode8.3
        - xcode9.4
cache: packages
r_check_args: "--as-cran"
r:
 - oldrel
 - release
 - devel
r_packages:
 - covr
 - devtools
 - testthat
after_success:
 - R -e 'covr::codecov()'
