language: r
sudo: required
dist: trusty
cache: packages
r_check_args: "--as-cran"
r:
 - oldrel
 - release
 - devel
os:
 - linux
 - osx
osx_image:
 - xcode9.4
 - xcode8.3
r_packages:
 - covr
 - devtools
after_success:
 - R -e 'covr::codecov()'
