language: r
sudo: required
dist: trusty
cache: packages
r_check_args: "--as-cran"
r:
 - oldrel
 - release
 - devel
os:
  - linux
  - osx
r_packages:
  - covr
  - devtools
after_success:
 - R -e 'covr::codecov()'
